const form=document.getElementById("form")
const username=document.getElementById("username")
const email=document.getElementById("email")
const password=document.getElementById("pass")
const conpassword=document.getElementById("conpassword")
